# アプリケーションのルーティングと主要なページコンポーネント構成
app:
  layout.tsx:
    role: "ルートレイアウト"
    description: "全ページ共通のレイアウトを定義"
    dependencies:
      - "next/font/google"
      - "./globals.css"

  page.tsx:
    role: "トップページ"
    description: "認証状態に基づくリダイレクト制御"
    dependencies:
      - "next-auth"
      - "next/navigation"
      - "./api/auth/[...nextauth]/route"

  (authenticated):
    todos/page.tsx:
      role: "Todoリストページ"
      description: "認証済みユーザーのTodo管理画面"
      dependencies:
        - "@/components/todo/todo-list"
        - "@/components/todo/todo-form"
        - "next-auth"
        - "@prisma/client"
        - "./actions"

    todos/page.client.tsx:
      role: "Todoリストクライアントコンポーネント"
      description: "Todoリストのクライアントサイド実装"
      dependencies:
        - "@/components/todo/todo-list"
        - "@/components/todo/todo-form"
        - "./actions"
        - "@prisma/client"

    todos/actions.ts:
      role: "Todoアクション"
      description: "TodoのCRUD操作とサーバーアクション"
      dependencies:
        - "@/lib/prisma"
        - "next-auth"
        - "next/cache"

  api:
    auth/[...nextauth]/route.ts:
      role: "NextAuth設定"
      description: "認証プロバイダーと認証ロジックの設定"
      dependencies:
        - "next-auth"
        - "@auth/prisma-adapter"
        - "@/lib/prisma"
        - "next-auth/providers/*"
        - "bcryptjs"

    auth/signup/route.ts:
      role: "サインアップAPI"
      description: "ユーザー登録処理のAPI実装"
      dependencies:
        - "next/server"
        - "bcryptjs"
        - "@/lib/prisma"
        - "@/lib/utils"

  auth:
    layout.tsx:
      role: "認証レイアウト"
      description: "認証ページの共通レイアウトと認証制御"
      dependencies:
        - "next-auth"
        - "next/navigation"

    login/page.tsx:
      role: "ログインページ"
      description: "ユーザーログインフォーム"
      dependencies:
        - "next-auth/react"
        - "next/navigation"
        - "@/components/ui/*"
        - "react-icons/*"

    signup/page.tsx:
      role: "サインアップページ"
      description: "ユーザー登録フォーム"
      dependencies:
        - "next/navigation"
        - "@/components/ui/*"
        - "@/lib/utils"