# アプリケーションのルーティングと主要なページコンポーネント構成
app:
  layout.tsx:
    role: "ルートレイアウト"
    description: "全ページ共通のレイアウトを定義"
    dependencies:
      - "@/components/layout/header"
      - "@/components/layout/footer"
      - "@/lib/utils"
  
  page.tsx:
    role: "トップページ"
    description: "アプリケーションのメインページ"
    dependencies:
      - "@/components/todo/todo-list"
      - "@/components/todo/todo-form"
      - "@/hooks/useTodos"

  error.tsx:
    role: "エラーページ"
    description: "エラー発生時の表示画面"
    dependencies:
      - "@/components/ui/button"

  loading.tsx:
    role: "ローディングUI"
    description: "ページ読み込み中の表示"
    dependencies:
      - "@/components/ui/loading"

  api:
    todos/route.ts:
      role: "Todo CRUD API"
      description: "TodoのRESTful API実装"
      dependencies:
        - "@/services/todoService"
        - "@/utils/validation"
        - "@/types/todo"
    
    auth/route.ts:
      role: "認証 API"
      description: "認証関連のAPI実装"
      dependencies:
        - "@/services/authService"
        - "@/utils/jwt"
        - "@/types/auth"

  auth:
    login/page.tsx:
      role: "ログインページ"
      description: "ユーザーログイン画面"
      dependencies:
        - "@/components/ui/input"
        - "@/components/ui/button"
        - "@/services/authService"

    signup/page.tsx:
      role: "サインアップページ"
      description: "ユーザー登録画面"
      dependencies:
        - "@/components/ui/input"
        - "@/components/ui/button"
        - "@/services/authService"

    layout.tsx:
      role: "認証ページレイアウト"
      description: "認証関連ページの共通レイアウト"
      dependencies:
        - "@/components/layout/header" 